/*
				echo '<tr>';
					echo '<td width="70%">';
						echo '<strong>';
						echo 'Ficha de Inscripci&oacute;n:';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_soli.php?codigo='.$cod.'\')">';
            			echo '<i class="fa fa-print" style="border-color: #f14c28;color: #f14c28;"></i>';
						echo '</a>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo '<strong>';
						echo 'Solicitud del postulante:';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_solicitud.php?codigo='.$cod.'\')">';
            			echo '<i class="fa fa-print" style="border-color: #006;color: #006;"></i>';
						echo '</a>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo '<strong>';
						echo 'Declaraci&oacute;n Jurada:';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_dj.php?codigo='.$cod.'\')">';
            		echo '<i class="fa fa-print" style="border-color: #066;color: #066;"></i>';
					echo '</a>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td width="70%">';
						echo '<strong>';
						echo 'Declaración Jurada de Aceptaci&oacute;n';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_aceptacion.php?codigo='.$cod.'\')">';
            			echo '<i class="fa fa-print" style="border-color: #66CC99;color: #66CC99;"></i>';
						echo '</a>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo '<strong>';
						echo 'Riesgos examen de admisi&oacute;n:';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_riesgos.php?codigo='.$cod.'\')">';
            			echo '<i class="fa fa-print" style="border-color: #C09;color: #C09;"></i>';
						echo '</a>';
					echo '</td>';
				echo '</tr>';
				echo '<tr>';
					echo '<td>';
						echo '<strong>';
						echo 'Requisitos m&iacute;nimos:';
						echo '</strong>';
					echo '</td>';
					echo '<td>';
						echo '<a href="javascript:ventanaSecundaria(\''.GL_DIR_WS_HTTP_APP.'zet/adm_post_requisitos.php?codigo='.$cod.'\')">';
            		echo '<i class="fa fa-print" style="border-color: #39C;color: #39C;"></i>';
					echo '</a>';
					echo '</td>';
				echo '</tr>';
				*/